name: PlayEffect
main: me.fromgate.playeffect.PlayEffectPlugin
version: 0.5.5
website: http://fromgate.me
author: fromgate, fromgate@gmail.com
softdepend: [WorldEdit,WorldGuard]
commands:
   playeffect:
      aliases: [play,pef,pe]
      description:
      usage:
           /playeffect help